CREATE DATABASE IF NOT EXISTS etudiants;

USE etudiants;

CREATE TABLE IF NOT EXISTS etudiant (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(100),
  prenom VARCHAR(100),
  email VARCHAR(100)
);
